title: Derrick Dryer
description: Systems, servers, and stories from the homelab.
baseurl: ""
url: https://www.derrickdryer.xyz

theme: cvless

# site settings
taglong: "A portfolio and blog showcasing my journey from hardware support to Linux system administration."
tagshort: "Tech Portfolio & Blog"
cv: true

# author settings
author:
  name: Derrick Dryer
  email: contact@derrickdryer.xyz
photo: assets/files/photo.jpg
joblines:
  - Homelab & DevOps Practitioner
  - Linux • Containers • Cloud
  - Pittsburgh, PA
address: Pittsburgh, PA
phone: +1 412 480 6852

# profile links
profile:
  facebook: https://www.facebook.com/derrick.e.dryer
  x: https://x.com/cottontail_dev
  # mastodon: https://mastodon.social/@username
  # bluesky: https://bsky.app/profile/username.bsky.social
  instagram: https://www.instagram.com/derrick.e.dryer
  linkedin: https://www.linkedin.com/in/ddryer007
  # xing: https://www.xing.com/profile/username
  # stackoverflow: https://stackoverflow.com/users/0000000/username
  # medium: https://medium.com/@username
  github: https://github.com/derrickdryer

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
